name: basic_shell
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.2
  path: ^1.9.0
  sdl2: ^1.7.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
